#!/bin/bash
export RECOVERY_FLAG_DIR=/var/log/fz-recovery-setup
export RECOVERY_EXECUTABLE=/usr/bin/fz-recovery-setup.sh

if [[ -f "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_0" ]]; then
    sh "${RECOVERY_EXECUTABLE}"
    rm "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_0"
    exit
fi
if [[ -f "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_1" ]]; then
    mv "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_1" "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_0"
    exit
fi
if [[ -f "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_2" ]]; then
    mv "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_2" "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_1"
    exit
fi
if [[ -f "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_3" ]]; then
    mv "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_3" "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_2"
    exit
fi
if [[ -f "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_4" ]]; then
    mv "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_4" "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_3"
    exit
fi
if [[ -f "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_5" ]]; then
    mv "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_5" "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_4"
    exit
fi

touch "${RECOVERY_FLAG_DIR}/RECOVERY_MODE_FLAG_NA"
