[http]
[http.routers]
[http.routers.mopidy]
#rule = "Host(`fzbox.local`)"
rule = "PathRegexp(`.*`)"
entryPoints = ["web", "websecure"]
service = "mopidy"

[http.services]
[http.services.mopidy.loadBalancer]
[[http.services.mopidy.loadBalancer.servers]]
url = "http://localhost:6680"
