http:
  routers:
    filebrowser:
      rule: "PathPrefix(`/browser`)"
      entryPoints:
        - "web"
        - "websecure"
      service: "filebrowser"

  services:
    filebrowser:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"
