http:
  routers:
    filebrowser:
      rule: "PathPrefix(`/browser`)"
      entryPoints:
        - "web"
        - "websecure"
      service: "filebrowser"
      middlewares:
        - "redirect-to-https"
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    filebrowser:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"
