http:
  routers:
    mopidy:
      rule: "PathRegexp(`.*`)"
      entryPoints:
        - "web"
        - "websecure"
      service: "mopidy"
      middlewares:
        - "redirect-to-https"

  services:
    mopidy:
      loadBalancer:
        servers:
          - url: "http://localhost:6680"
