http:
  routers:
    mopidy:
      rule: "PathRegexp(`.*`)"
      entryPoints:
        - "web"
        - "websecure"
      service: "mopidy"
      middlewares:
        - "redirect-to-https"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    mopidy:
      loadBalancer:
        servers:
          - url: "http://localhost:6680"
