[[tls.certificates]]
certFile = "/home/afzalex/serversetup/traefik/ssl/fzbox.local.crt"
keyFile = "/home/afzalex/serversetup/traefik/ssl/fzbox.local.key"



[tls.stores]
[tls.stores.default]
[tls.stores.default.defaultCertificate]
certFile = "/home/afzalex/serversetup/traefik/ssl/fzbox.local.crt"
keyFile = "/home/afzalex/serversetup/traefik/ssl/fzbox.local.key"